spring.application.name=demo
# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/pr_company?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=2345anvv

# Tell Hibernate to automatically create your tables!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true